# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
